### ISSUE TITLE
Improve documentation - Require DotEnv VsCode Extension

### ISSUE THREAD

**Issue by Maxgoods62** [johnpapa/vscode-cloak#20]
First, thanks for the extension, it's usefull !

During installation, I couldn't get it to work. I disabled all my extensions, changed theme: it still didn't work.

I understood afterwards that it was necessary to install the DotENV extension, because without it, .env files are considered as plain text.

So, it might help other people to add a line in the documentation saying to install Dotenv.

**Comment by tschaeff** [comment]
You, sir, are my hero, thank you!

**Comment by johnpapa** [comment]
Thanks

We are open for contributors too

**Comment by johnpapa** [comment]
I made this an automatic extension dependency in v0.3.0

this way it installs dotenv for you
