### ISSUE TITLE
"global" error

### ISSUE THREAD

**Issue by JimLynchCodes** [johnpapa/vscode-cloak#42]
When I install this extension and try to use it, it just gives me an error...

![Screen Shot 2021-08-04 at 10 20 39 AM](https://user-images.githubusercontent.com/5354163/128197909-52d84af7-1e97-4bcb-8d25-ca7703132a79.png)

**Comment by JimLynchCodes** [comment]
I have no clue what it is referring to by "the global command"

**Comment by johnpapa** [comment]
This is referrring to an extension named "Pascal", not Cloak.
